Quick Start
-----------

This part of the docs gets you started quickly.

.. toctree::
   :maxdepth: 2

   quickstart/first_step

API Documentation
-----------------

This part tells you which methods you may want to call.

.. toctree::
   :maxdepth: 2

   api/grss

Database Schema
---------------

This part tells you about the SQLite3 database schema used

.. toctree::
   :maxdepth: 2

   schema/sqlite3